- name: upgrade the kernel
  hosts: servers
  become: true
  vars:
    kernelversion: 3.10.0-1062.4.3.el7.x86_64
  tasks:
    
    - name: upgrade the kernel
      yum:
        name: kernel-{{ kernelversion}}
        state: present

    - name: reboot
      reboot:

    - debug:
        msg: Kernel Version {{ ansible_kernel }}

    - name: delete last kernel
      command: package-cleanup --oldkernels --count=1 -y

    - name: reboot
      reboot:

