- name: upgrade the kernel
  hosts: servers
  become: true
  tasks:
    - debug:
        msg: "{{ ansible_kernel }}"
      register: ansiblekernel

    - block:
      - name: upgrade the kernel
        yum:
          name: kernel-{{ kernelversion}}
          state: present

      - name: reboot
        reboot:


      - name: delete last kernel
        command: package-cleanup --oldkernels --count=1 -y

      - name: reboot
        reboot:

      when: "{{ actualkernel in ansiblekernel.msg }}"
